name: Build and Release on macOS

on:
  push:
    branches:
      - actions
  pull_request:
    branches:
      - actions

jobs:
  build-and-release:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Install Homebrew
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> ~/.zprofile
        eval "$(/opt/homebrew/bin/brew shellenv)"
    
    - name: Debug PATH and Commands Before
      run: |
        echo "Current PATH: $PATH"
        which python3 || echo "python3 not found"
        which node || echo "node not found"
        which npm || echo "npm not found"
        ls -al $(npm config get prefix)/bin || echo "npm bin not found"

    - name: Install Python 3.12 and Update PATH
      run: |
        brew install python@3.12
        echo 'export PATH="/opt/homebrew/opt/python@3.12/bin:$PATH"' >> ~/.zprofile
        echo 'export PATH="/opt/homebrew/opt/python@3.12/bin:$PATH"' >> ~/.bash_profile
        export PATH="/opt/homebrew/opt/python@3.12/bin:$PATH"
        source ~/.zprofile
        python3 --version
  
    #- name: Use Node.js LTS
    #  uses: actions/setup-node@v3
    #  with:
    #    node-version: '20.x'
    #    cache: 'npm'

    #- name: Set Python
    #  run: |
    #    export PYTHON=$(which python3)
    
    - name: Debug Python Version and PATH
      run: |
        which python3
        python3 --version
        echo "Current PATH: $PATH"

    - name: Debug PATH and Commands After
      run: |
        echo "Current PATH: $PATH"
        which python3 || echo "python3 not found"
        which node || echo "node not found"
        which npm || echo "npm not found"
        ls -al $(npm config get prefix)/bin || echo "npm bin not found"

    - name: Install dependencies
      run: |
        brew install git cmake pkg-config node
    
    - name: Debug PATH and Commands After Dependencies
      run: |
        echo "Current PATH: $PATH"
        which python3 || echo "python3 not found"
        which node || echo "node not found"
        which npm || echo "npm not found"
        ls -al $(npm config get prefix)/bin || echo "npm bin not found"

    - name: Print directory structure before configuring backend
      run: |
        echo "Directory structure BEFORE configuring backend:"
        ls -R ${{ github.workspace }}

    - name: Configure backend
      run: |
        # Set macOS version
        macOS_vers_num=10.15

        # Navigate to backend directory
        cd ${{ github.workspace }}/backend

        # Check if vcpkg is properly set up
        if ! [ -f "vcpkg/bootstrap-vcpkg.sh" ]; then
          echo "vcpkg not set up or incomplete, initializing..."
          rm -rf vcpkg  # Ensure a clean state
          git clone https://github.com/microsoft/vcpkg
          sh vcpkg/bootstrap-vcpkg.sh

          # Append minimum macOS version to vcpkg/triplets/x64-osx.cmake
          echo "set(VCPKG_C_FLAGS -mmacosx-version-min=$macOS_vers_num)" >> vcpkg/triplets/x64-osx.cmake
          echo "set(VCPKG_CXX_FLAGS -mmacosx-version-min=$macOS_vers_num)" >> vcpkg/triplets/x64-osx.cmake
        fi

        # Check for vcpkg updates
        cd vcpkg
        git pull --ff-only
        sh bootstrap-vcpkg.sh
        cd ..

        # Install dependencies
        export MACOSX_DEPLOYMENT_TARGET=$macOS_vers_num
        export VCPKG_OSX_DEPLOYMENT_TARGET=$macOS_vers_num
        export VCPKG_KEEP_ENV_VARS="VCPKG_OSX_DEPLOYMENT_TARGET;MACOSX_DEPLOYMENT_TARGET"
        packages=$(cat "dependencies.txt")
        for p in $packages
        do
          ./vcpkg/vcpkg install $p
        done

    - name: Print directory structure after configuring backend
      run: |
        echo "Directory structure AFTER configuring backend:"
        ls -R ${{ github.workspace }}

    - name: Set Python for npm globally
      run: |
        export PATH="/opt/homebrew/opt/python@3.12/bin:$PATH"
        npm config set python /opt/homebrew/opt/python@3.12/bin/python3.12
        npm config get python

    - name: Debug Python Version and PATH
      run: |
        which python3
        python3 --version
        echo "Current PATH: $PATH"

    - name: Set up frontend
      run: |
        export PATH="/opt/homebrew/opt/python@3.12/bin:$PATH"
        export PYTHON=$(which python3)
        cd ${{ github.workspace }}/frontend
        echo "Using Python for npm: $PYTHON"
        npm ci

    - name: Build backend
      run: |
        cd ${{ github.workspace }}/backend
        sh osx_release.sh

    - name: Release frontend
      run: |
        cd ${{ github.workspace }}/frontend
        sh release_frontend.sh

    - name: Upload macOS application artifact
      uses: actions/upload-artifact@v4
      with:
        name: Beyond_RGB-darwin-x64
        path: ${{ github.workspace }}/frontend/out/Beyond_RGB-darwin-x64
